[package]
name = "sst-rust"
version = "0.1.0"
authors = ["Eelco Dolstra <edolstra@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
clap = "2"
libc = "0.2"
