[package]
name = "sst"
version = "0.1.0"
authors = ["Eelco Dolstra <edolstra@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
clap = "2"
libc = "0.2"
nom = "5.0"
nom_locate = "0.4"